### ISSUE TITLE
缺少方法 get_exl_data_v2

### ISSUE THREAD

**Issue by Black19** [Liang-yc/ssq#22]
问题一
缺少这个方法，
get_exl_data_v2

问题二：
Traceback (most recent call last):
  File "ssq4all.py", line 121, in <module>
    tf.compat.v1.app.run()
    raise ValueError(
ValueError: Cannot feed value of shape (2656, 1, 7, 1) for Tensor 'Placeholder:0', which has shape '(2656, 1, 13, 1)'

**Comment by Black19** [comment]
> 问题一
> 缺少这个方法，
> get_exl_data_v2
> 
> 问题二：
> Traceback (most recent call last):
> File "ssq4all.py", line 121, in
> tf.compat.v1.app.run()
> raise ValueError(
> ValueError: Cannot feed value of shape (2656, 1, 7, 1) for Tensor 'Placeholder:0', which has shape '(2656, 1, 13, 1)'
